platform: "Windows 10"
browser: "Chrome"
browserVersion: "140.0.7339.186"
 
lambdatest:
  user: "<m-naveen.b.kumar@capgemini.com>"
  accessKey: "<LT_U9QUwERvCXqr5BD6XD6Xty0R4j6nOyBzb47wCIXqQzoq5VL>"
  seleniumHub: "http://hub.lambdatest.com/wd/hub"
 
testSuites:
  - name: LambdaTest
    classes:
      - LambdaTestTesting.Lambdatestscenarios.LambdatestScenarios2
      - LambdaTestTesting.Lambdatestscenarios.LambdatestScenarios3
      - LambdaTestTesting.Lambdatestscenarios.LambdatestScenario1
 
